export const data = [
    {
        id: 1,
        name: "Áo Polo cổ V chất cotton co giãn 4 chiều",
        collab: "Adidas",
        price: 100,
        star: 5,
        description: "This Limited Edition printed t-shirt marks the rebirth of a phoenix. With a hand drawn design artwork symbolizing a greater resurrection of an immortal creature with our text detail featuring the new collection name and product details. Each layer is hand printed with care.",
        images: [
            "./assets/Áo Polo cổ V chất cotton co giãn 4 chiều/1.jpg",
            "./assets/Áo Polo cổ V chất cotton co giãn 4 chiều/2.jpg",
            "./assets/Áo Polo cổ V chất cotton co giãn 4 chiều/3.jpg",
            "./assets/Áo Polo cổ V chất cotton co giãn 4 chiều/4.jpg",
            "./assets/Áo Polo cổ V chất cotton co giãn 4 chiều/5.jpg",
            "./assets/Áo Polo cổ V chất cotton co giãn 4 chiều/6.jpg",
            "./assets/Áo Polo cổ V chất cotton co giãn 4 chiều/7.jpg",
            "./assets/Áo Polo cổ V chất cotton co giãn 4 chiều/8.jpg",
            "./assets/Áo Polo cổ V chất cotton co giãn 4 chiều/9.jpg",
            "./assets/Áo Polo cổ V chất cotton co giãn 4 chiều/10.jpg",
            "./assets/Áo Polo cổ V chất cotton co giãn 4 chiều/11.jpg",
            "./assets/Áo Polo cổ V chất cotton co giãn 4 chiều/12.jpg",
            "./assets/Áo Polo cổ V chất cotton co giãn 4 chiều/13.jpg",
            "./assets/Áo Polo cổ V chất cotton co giãn 4 chiều/14.jpg",
        ]
    },
    {
        id: 2,
        name: "áo polo dài tay khoá kéo (đen trắng)",
        collab: "Nike",
        price: 100,
        star: 5,
        description: "This Limited Edition printed t-shirt marks the rebirth of a phoenix. With a hand drawn design artwork symbolizing a greater resurrection of an immortal creature with our text detail featuring the new collection name and product details. Each layer is hand printed with care.",
        images: [
            `./assets/áo polo dài tay khoá kéo (đen trắng)/1.jpg`,
            `./assets/áo polo dài tay khoá kéo (đen trắng)/2.jpg`,
            `./assets/áo polo dài tay khoá kéo (đen trắng)/3.jpg`,
            `./assets/áo polo dài tay khoá kéo (đen trắng)/4.jpg`,
            `./assets/áo polo dài tay khoá kéo (đen trắng)/5.jpg`,
            `./assets/áo polo dài tay khoá kéo (đen trắng)/6.jpg`,
        ]
    },
    {
        id: 3,
        name: "Áo polo khoá kéo 3 màu (đen xám trắng)",
        collab: "Addidas",
        price: 100,
        start: 5,
        description: "This Limited Edition printed t-shirt marks the rebirth of a phoenix. With a hand drawn design artwork symbolizing a greater resurrection of an immortal creature with our text detail featuring the new collection name and product details. Each layer is hand printed with care.",
        images: [
            "./assets/Áo polo khoá kéo 3 màu (đen xám trắng)/1.jpg",
            "./assets/Áo polo khoá kéo 3 màu (đen xám trắng)/2.jpg",
            "./assets/Áo polo khoá kéo 3 màu (đen xám trắng)/3.jpg",
            "./assets/Áo polo khoá kéo 3 màu (đen xám trắng)/4.jpg",
            "./assets/Áo polo khoá kéo 3 màu (đen xám trắng)/5.jpg",
            "./assets/Áo polo khoá kéo 3 màu (đen xám trắng)/6.jpg",
            "./assets/Áo polo khoá kéo 3 màu (đen xám trắng)/7.jpg",
        ]
    },
    {
        id: 4,
        name: "Áo sơ mi cổ trụ form slim fit (đen trắng)",
        collab: "Addidas",
        price: 100,
        start: 5,
        description: "This Limited Edition printed t-shirt marks the rebirth of a phoenix. With a hand drawn design artwork symbolizing a greater resurrection of an immortal creature with our text detail featuring the new collection name and product details. Each layer is hand printed with care.",
        images: [
            "./assets/Áo sơ mi cổ trụ form slim fit (đen trắng)/1.jpg",
            "./assets/Áo sơ mi cổ trụ form slim fit (đen trắng)/2.jpg",
            "./assets/Áo sơ mi cổ trụ form slim fit (đen trắng)/3.jpg",
            "./assets/Áo sơ mi cổ trụ form slim fit (đen trắng)/4.jpg",
            "./assets/Áo sơ mi cổ trụ form slim fit (đen trắng)/5.jpg",
        ]
    },
    {
        id: 5,
        name: "Áo sơ mi form slimfit co giãn 4 chiều (đen trắng)",
        collab: "Addidas",
        price: 100,
        start: 5,
        description: "This Limited Edition printed t-shirt marks the rebirth of a phoenix. With a hand drawn design artwork symbolizing a greater resurrection of an immortal creature with our text detail featuring the new collection name and product details. Each layer is hand printed with care.",
        images: [
            "./assets/Áo sơ mi form slimfit co giãn 4 chiều (đen trắng)/1.jpg",
            "./assets/Áo sơ mi form slimfit co giãn 4 chiều (đen trắng)/2.jpg",
            "./assets/Áo sơ mi form slimfit co giãn 4 chiều (đen trắng)/3.jpg",
            "./assets/Áo sơ mi form slimfit co giãn 4 chiều (đen trắng)/4.jpg",
            "./assets/Áo sơ mi form slimfit co giãn 4 chiều (đen trắng)/5.jpg",
            "./assets/Áo sơ mi form slimfit co giãn 4 chiều (đen trắng)/6.jpg",
            "./assets/Áo sơ mi form slimfit co giãn 4 chiều (đen trắng)/7.jpg",
            "./assets/Áo sơ mi form slimfit co giãn 4 chiều (đen trắng)/8.jpg",
            "./assets/Áo sơ mi form slimfit co giãn 4 chiều (đen trắng)/9.jpg",
            "./assets/Áo sơ mi form slimfit co giãn 4 chiều (đen trắng)/10.jpg",
        ]
    },
    {
        id: 6,
        name: "Áo sơ mi ngắn tay  form slimfit co giãn 4 chiều",
        collab: "Addidas",
        price: 100,
        start: 5,
        description: "This Limited Edition printed t-shirt marks the rebirth of a phoenix. With a hand drawn design artwork symbolizing a greater resurrection of an immortal creature with our text detail featuring the new collection name and product details. Each layer is hand printed with care.",
        images: [
            "./assets/Áo sơ mi ngắn tay  form slimfit co giãn 4 chiều/1.jpg",
            "./assets/Áo sơ mi ngắn tay  form slimfit co giãn 4 chiều/2.jpg",
            "./assets/Áo sơ mi ngắn tay  form slimfit co giãn 4 chiều/3.jpg",
            "./assets/Áo sơ mi ngắn tay  form slimfit co giãn 4 chiều/4.jpg",
            "./assets/Áo sơ mi ngắn tay  form slimfit co giãn 4 chiều/5.jpg"
        ]
    },
    {
        id: 7,
        name: "áo tshirt oversize xám tro",
        collab: "Addidas",
        price: 100,
        start: 5,
        description: "This Limited Edition printed t-shirt marks the rebirth of a phoenix. With a hand drawn design artwork symbolizing a greater resurrection of an immortal creature with our text detail featuring the new collection name and product details. Each layer is hand printed with care.",
        images: [
            "./assets/áo tshirt oversize xám tro/1.jpg",
            "./assets/áo tshirt oversize xám tro/2.jpg",
            "./assets/áo tshirt oversize xám tro/3.jpg",
            "./assets/áo tshirt oversize xám tro/4.jpg"
        ]
    },
    {
        id: 8,
        name: "Áo Tshirt slimfit cotton 100",
        collab: "Addidas",
        price: 100,
        start: 5,
        description: "This Limited Edition printed t-shirt marks the rebirth of a phoenix. With a hand drawn design artwork symbolizing a greater resurrection of an immortal creature with our text detail featuring the new collection name and product details. Each layer is hand printed with care.",
        images: [
            "./assets/Áo Tshirt slimfit cotton 100/1.jpg",
            "./assets/Áo Tshirt slimfit cotton 100/2.jpg",
            "./assets/Áo Tshirt slimfit cotton 100/3.jpg",
            "./assets/Áo Tshirt slimfit cotton 100/4.jpg",
            "./assets/Áo Tshirt slimfit cotton 100/5.jpg",
            "./assets/Áo Tshirt slimfit cotton 100/6.jpg",
            "./assets/Áo Tshirt slimfit cotton 100/7.jpg"
        ]
    },
    {
        id: 9,
        name: "chinos đen co giãn 4 chiều",
        collab: "Addidas",
        price: 100,
        start: 5,
        description: "This Limited Edition printed t-shirt marks the rebirth of a phoenix. With a hand drawn design artwork symbolizing a greater resurrection of an immortal creature with our text detail featuring the new collection name and product details. Each layer is hand printed with care.",
        images: [
            "./assets/chinos đen co giãn 4 chiều/1.jpg",
            "./assets/chinos đen co giãn 4 chiều/2.jpg",
            "./assets/chinos đen co giãn 4 chiều/3.jpg",
        ]
    },
    {
        id: 10,
        name: "Henly Light Wash",
        collab: "Addidas",
        price: 100,
        start: 5,
        description: "This Limited Edition printed t-shirt marks the rebirth of a phoenix. With a hand drawn design artwork symbolizing a greater resurrection of an immortal creature with our text detail featuring the new collection name and product details. Each layer is hand printed with care.",
        images: [
            "./assets/henlyLightWash/1.jpg",
            "./assets/henlyLightWash/2.jpg",
            "./assets/henlyLightWash/3.jpg",
            "./assets/henlyLightWash/4.jpg",
            "./assets/henlyLightWash/5.jpg",
            "./assets/henlyLightWash/6.jpg",
        ]
    },
    {
        id: 11,
        name: "oversize cổ lửng cotton (đen  trắng)",
        collab: "Addidas",
        price: 100,
        start: 5,
        description: "This Limited Edition printed t-shirt marks the rebirth of a phoenix. With a hand drawn design artwork symbolizing a greater resurrection of an immortal creature with our text detail featuring the new collection name and product details. Each layer is hand printed with care.",
        images: [
            "./assets/oversize cổ lửng cotton (đen  trắng)/1.jpg",
            "./assets/oversize cổ lửng cotton (đen  trắng)/2.jpg",
            "./assets/oversize cổ lửng cotton (đen  trắng)/3.jpg",
            "./assets/oversize cổ lửng cotton (đen  trắng)/4.jpg",
            "./assets/oversize cổ lửng cotton (đen  trắng)/5.jpg",
            "./assets/oversize cổ lửng cotton (đen  trắng)/6.jpg",
            "./assets/oversize cổ lửng cotton (đen  trắng)/7.jpg",
        ]
    },
    {
        id: 12,
        name: "quần âu đen cropped co giãn 4 chiều",
        collab: "Addidas",
        price: 100,
        start: 5,
        description: "This Limited Edition printed t-shirt marks the rebirth of a phoenix. With a hand drawn design artwork symbolizing a greater resurrection of an immortal creature with our text detail featuring the new collection name and product details. Each layer is hand printed with care.",
        images: [
            "./assets/quần âu đen cropped co giãn 4 chiều/1.jpg",
            "./assets/quần âu đen cropped co giãn 4 chiều/2.jpg",
            "./assets/quần âu đen cropped co giãn 4 chiều/3.jpg",
        ]
    },
    {
        id: 13,
        name: "quần âu kẻ caro co giãn 4 chiều",
        collab: "Addidas",
        price: 100,
        start: 5,
        description: "This Limited Edition printed t-shirt marks the rebirth of a phoenix. With a hand drawn design artwork symbolizing a greater resurrection of an immortal creature with our text detail featuring the new collection name and product details. Each layer is hand printed with care.",
        images: [
            "./assets/quần âu kẻ caro co giãn 4 chiều/1.jpg",
            "./assets/quần âu kẻ caro co giãn 4 chiều/2.jpg",
            "./assets/quần âu kẻ caro co giãn 4 chiều/3.jpg",
        ]
    },
    {
        id: 14,
        name: "quần âu xám co giãn 4 chiều",
        collab: "Addidas",
        price: 100,
        start: 5,
        description: "This Limited Edition printed t-shirt marks the rebirth of a phoenix. With a hand drawn design artwork symbolizing a greater resurrection of an immortal creature with our text detail featuring the new collection name and product details. Each layer is hand printed with care.",
        images: [
            "./assets/quần âu xám co giãn 4 chiều/1.jpg",
            "./assets/quần âu xám co giãn 4 chiều/2.jpg",
            "./assets/quần âu xám co giãn 4 chiều/3.jpg",
            "./assets/quần âu xám co giãn 4 chiều/4.jpg",
        ]
    },
    {
        id: 15,
        name: "short jean rách co giãn 4 chiều (xanh đen)",
        collab: "Addidas",
        price: 100,
        start: 5,
        description: "This Limited Edition printed t-shirt marks the rebirth of a phoenix. With a hand drawn design artwork symbolizing a greater resurrection of an immortal creature with our text detail featuring the new collection name and product details. Each layer is hand printed with care.",
        images: [
            "./assets/short jean rách co giãn 4 chiều (xanh đen)/1.jpg",
            "./assets/short jean rách co giãn 4 chiều (xanh đen)/2.jpg",
            "./assets/short jean rách co giãn 4 chiều (xanh đen)/3.jpg",
            "./assets/short jean rách co giãn 4 chiều (xanh đen)/4.jpg",
            "./assets/short jean rách co giãn 4 chiều (xanh đen)/5.jpg",
            "./assets/short jean rách co giãn 4 chiều (xanh đen)/6.jpg",
            "./assets/short jean rách co giãn 4 chiều (xanh đen)/7.jpg",
            "./assets/short jean rách co giãn 4 chiều (xanh đen)/8.jpg",
        ]
    },
    {
        id: 16,
        name: "short jeans trơn co giãn 4 chiều (đen xanh)",
        collab: "Addidas",
        price: 100,
        start: 5,
        description: "This Limited Edition printed t-shirt marks the rebirth of a phoenix. With a hand drawn design artwork symbolizing a greater resurrection of an immortal creature with our text detail featuring the new collection name and product details. Each layer is hand printed with care.",
        images: [
            "./assets/short jeans trơn co giãn 4 chiều (đen xanh)/1.jpg",
            "./assets/short jeans trơn co giãn 4 chiều (đen xanh)/2.jpg",
            "./assets/short jeans trơn co giãn 4 chiều (đen xanh)/3.jpg",
            "./assets/short jeans trơn co giãn 4 chiều (đen xanh)/4.jpg",
            "./assets/short jeans trơn co giãn 4 chiều (đen xanh)/5.jpg",
            "./assets/short jeans trơn co giãn 4 chiều (đen xanh)/6.jpg",
            "./assets/short jeans trơn co giãn 4 chiều (đen xanh)/7.jpg",
            "./assets/short jeans trơn co giãn 4 chiều (đen xanh)/8.jpg",
            "./assets/short jeans trơn co giãn 4 chiều (đen xanh)/9.jpg",
            "./assets/short jeans trơn co giãn 4 chiều (đen xanh)/10.jpg",
        ]
    },
    {
        id: 17,
        name: "skinny jean rách các loại (đen xanh)",
        collab: "Addidas",
        price: 100,
        start: 5,
        description: "This Limited Edition printed t-shirt marks the rebirth of a phoenix. With a hand drawn design artwork symbolizing a greater resurrection of an immortal creature with our text detail featuring the new collection name and product details. Each layer is hand printed with care.",
        images: [
            "./assets/skinny jean rách các loại (đen xanh)/1.jpg",
            "./assets/skinny jean rách các loại (đen xanh)/2.jpg",
            "./assets/skinny jean rách các loại (đen xanh)/3.jpg",
            "./assets/skinny jean rách các loại (đen xanh)/4.jpg",
            "./assets/skinny jean rách các loại (đen xanh)/5.jpg",
            "./assets/skinny jean rách các loại (đen xanh)/6.jpg",
            "./assets/skinny jean rách các loại (đen xanh)/7.jpg",
            "./assets/skinny jean rách các loại (đen xanh)/8.jpg",
            "./assets/skinny jean rách các loại (đen xanh)/9.jpg",
        ]
    },
    {
        id: 18,
        name: "skinny jeans đen rách khoá kéo(gối+đùi) co giãn 4 chiều",
        collab: "Addidas",
        price: 100,
        start: 5,
        description: "This Limited Edition printed t-shirt marks the rebirth of a phoenix. With a hand drawn design artwork symbolizing a greater resurrection of an immortal creature with our text detail featuring the new collection name and product details. Each layer is hand printed with care.",
        images: [
            "./assets/skinny jeans đen rách khoá kéo(gối+đùi) co giãn 4 chiều/1.jpg",
            "./assets/skinny jeans đen rách khoá kéo(gối+đùi) co giãn 4 chiều/2.jpg",
            "./assets/skinny jeans đen rách khoá kéo(gối+đùi) co giãn 4 chiều/3.jpg",
        ]
    },
    {
        id: 19,
        name: "skinny jeans rách gối co giãn chiều(đen xanh)",
        collab: "Addidas",
        price: 100,
        start: 5,
        description: "This Limited Edition printed t-shirt marks the rebirth of a phoenix. With a hand drawn design artwork symbolizing a greater resurrection of an immortal creature with our text detail featuring the new collection name and product details. Each layer is hand printed with care.",
        images: [
            "./assets/skinny jeans rách gối co giãn chiều(đen xanh)/1.jpg",
            "./assets/skinny jeans rách gối co giãn chiều(đen xanh)/2.jpg",
            "./assets/skinny jeans rách gối co giãn chiều(đen xanh)/3.jpg",
            "./assets/skinny jeans rách gối co giãn chiều(đen xanh)/4.jpg",
            "./assets/skinny jeans rách gối co giãn chiều(đen xanh)/5.jpg",
            "./assets/skinny jeans rách gối co giãn chiều(đen xanh)/6.jpg",
            "./assets/skinny jeans rách gối co giãn chiều(đen xanh)/7.jpg",
            "./assets/skinny jeans rách gối co giãn chiều(đen xanh)/8.jpg",
            "./assets/skinny jeans rách gối co giãn chiều(đen xanh)/9.jpg",
            "./assets/skinny jeans rách gối co giãn chiều(đen xanh)/10.jpg",
        ]
    },
    {
        id: 20,
        name: "skinny jeans trắng rách co giãn 4 chiều",
        collab: "Addidas",
        price: 100,
        start: 5,
        description: "This Limited Edition printed t-shirt marks the rebirth of a phoenix. With a hand drawn design artwork symbolizing a greater resurrection of an immortal creature with our text detail featuring the new collection name and product details. Each layer is hand printed with care.",
        images: [
            "./assets/skinny jeans trắng rách co giãn 4 chiều/1.png",
            "./assets/skinny jeans trắng rách co giãn 4 chiều/2.png",
            "./assets/skinny jeans trắng rách co giãn 4 chiều/3.png",
        ]
    },
    {
        id: 21,
        name: "skinny jeans trơn co giãn 4 chiều (đen xanh)",
        collab: "Addidas",
        price: 100,
        start: 5,
        description: "This Limited Edition printed t-shirt marks the rebirth of a phoenix. With a hand drawn design artwork symbolizing a greater resurrection of an immortal creature with our text detail featuring the new collection name and product details. Each layer is hand printed with care.",
        images: [
            "./assets/skinny jeans trơn co giãn 4 chiều (đen xanh)/1.jpg",
            "./assets/skinny jeans trơn co giãn 4 chiều (đen xanh)/2.jpg",
            "./assets/skinny jeans trơn co giãn 4 chiều (đen xanh)/3.jpg",
            "./assets/skinny jeans trơn co giãn 4 chiều (đen xanh)/4.jpg",
            "./assets/skinny jeans trơn co giãn 4 chiều (đen xanh)/5.jpg",
            "./assets/skinny jeans trơn co giãn 4 chiều (đen xanh)/6.jpg",
            "./assets/skinny jeans trơn co giãn 4 chiều (đen xanh)/7.jpg",
            "./assets/skinny jeans trơn co giãn 4 chiều (đen xanh)/8.jpg",
            "./assets/skinny jeans trơn co giãn 4 chiều (đen xanh)/9.jpg",
        ]
    },
    {
        id: 22,
        name: "skinny Jeans xám tro rách co giãn 4 chiều",
        collab: "Addidas",
        price: 100,
        start: 5,
        description: "This Limited Edition printed t-shirt marks the rebirth of a phoenix. With a hand drawn design artwork symbolizing a greater resurrection of an immortal creature with our text detail featuring the new collection name and product details. Each layer is hand printed with care.",
        images: [
            "./assets/skinny Jeans xám tro rách co giãn 4 chiều/1.jpg",
            "./assets/skinny Jeans xám tro rách co giãn 4 chiều/2.jpg",
            "./assets/skinny Jeans xám tro rách co giãn 4 chiều/3.jpg",
            "./assets/skinny Jeans xám tro rách co giãn 4 chiều/4.jpg",
            "./assets/skinny Jeans xám tro rách co giãn 4 chiều/5.jpg",
            "./assets/skinny Jeans xám tro rách co giãn 4 chiều/6.jpg",
            "./assets/skinny Jeans xám tro rách co giãn 4 chiều/7.jpg",
        ]
    },
    {
        id: 23,
        name: "skinny Jeans xám tro rách gấu + gối khoá kéo",
        collab: "Addidas",
        price: 100,
        start: 5,
        description: "This Limited Edition printed t-shirt marks the rebirth of a phoenix. With a hand drawn design artwork symbolizing a greater resurrection of an immortal creature with our text detail featuring the new collection name and product details. Each layer is hand printed with care.",
        images: [
            "./assets/skinny Jeans xám tro rách gấu + gối khoá kéo/1.jpg",
            "./assets/skinny Jeans xám tro rách gấu + gối khoá kéo/2.jpg",
            "./assets/skinny Jeans xám tro rách gấu + gối khoá kéo/3.jpg",
            "./assets/skinny Jeans xám tro rách gấu + gối khoá kéo/4.jpg",
        ]
    },
    {
        id: 24,
        name: "skinny jeans xanh rách (gối+đùi) co giãn 4 chiều",
        collab: "Addidas",
        price: 100,
        start: 5,
        description: "This Limited Edition printed t-shirt marks the rebirth of a phoenix. With a hand drawn design artwork symbolizing a greater resurrection of an immortal creature with our text detail featuring the new collection name and product details. Each layer is hand printed with care.",
        images: [
           "./assets/skinny jeans xanh rách (gối+đùi) co giãn 4 chiều/1.png",
           "./assets/skinny jeans xanh rách (gối+đùi) co giãn 4 chiều/2.png",
           "./assets/skinny jeans xanh rách (gối+đùi) co giãn 4 chiều/3.png",
           "./assets/skinny jeans xanh rách (gối+đùi) co giãn 4 chiều/4.png",
           "./assets/skinny jeans xanh rách (gối+đùi) co giãn 4 chiều/5.png",
           "./assets/skinny jeans xanh rách (gối+đùi) co giãn 4 chiều/6.png",
           "./assets/skinny jeans xanh rách (gối+đùi) co giãn 4 chiều/7.png",
           "./assets/skinny jeans xanh rách (gối+đùi) co giãn 4 chiều/8.png",
           "./assets/skinny jeans xanh rách (gối+đùi) co giãn 4 chiều/9.png",
           "./assets/skinny jeans xanh rách (gối+đùi) co giãn 4 chiều/10.png",
           "./assets/skinny jeans xanh rách (gối+đùi) co giãn 4 chiều/11.png",
        ]
    },

]