
export const data = [
    {
        id: 1,
        collection: "New Arrival",
        name: "Áo Polo cổ V chất cotton co giãn 4 chiều",
        collab: "Adidas",
        price: 260.000,
        star: 5,
        description: ["NEW ARRIVAL POLP V LECK 2022",
                        "--> Đã Chán ngấy với kiểu polo thông thường với kiểu cúc hay khoá thì hôm nay Amey mang đến cho ae NEW MONSTER trong tháng này.",
                        "--> THANH LỊCH - SANG TRỌNG - MỚI MẺ là những gì ae có thể tìm được ở chiếc polo này. Vẫn chất cotton co giãn 4 chiều mang lại cảm giác thoải mái dễ chịu cho ngày hè.",
                        "--> Form size đầy đủ S M L XL Châu Âu cho ae.",
                        "Suggest size:Size S: 60-66kgSize M: 67-73kgSize L: 74-80kgSize XL: 81-86kg."],
        images: [
            "./assets/Áo Polo cổ V chất cotton co giãn 4 chiều/1.jpg",
            "./assets/Áo Polo cổ V chất cotton co giãn 4 chiều/2.jpg",
            "./assets/Áo Polo cổ V chất cotton co giãn 4 chiều/3.jpg",
            "./assets/Áo Polo cổ V chất cotton co giãn 4 chiều/4.jpg",
            "./assets/Áo Polo cổ V chất cotton co giãn 4 chiều/5.jpg",
            "./assets/Áo Polo cổ V chất cotton co giãn 4 chiều/6.jpg",
            "./assets/Áo Polo cổ V chất cotton co giãn 4 chiều/7.jpg",
            "./assets/Áo Polo cổ V chất cotton co giãn 4 chiều/8.jpg",
            "./assets/Áo Polo cổ V chất cotton co giãn 4 chiều/9.jpg",
            "./assets/Áo Polo cổ V chất cotton co giãn 4 chiều/10.jpg",
            "./assets/Áo Polo cổ V chất cotton co giãn 4 chiều/11.jpg",
            "./assets/Áo Polo cổ V chất cotton co giãn 4 chiều/12.jpg",
            "./assets/Áo Polo cổ V chất cotton co giãn 4 chiều/13.jpg",
            "./assets/Áo Polo cổ V chất cotton co giãn 4 chiều/14.jpg",
        ]
    },
    {
        id: 2,
        collection: "New Arrival",
        name: "áo polo dài tay khoá kéo (đen trắng)",
        collab: "Nike",
        price: 310.000,
        star: 5,
        description: ["Polo khoá Zip",
                    "Cho các tín đồ dòng polo muốn một chiếc áo lịch sự thì đây chính là siêu phẩm tiếp theo dành cho anh em. Khi biến anh em thành những quý ông cực LỊCH LÃM- SANG TRỌNG dễ phối đồ Mang đến chất liệu bông Cao Cấp co giãn 4 chiều cùng form dáng cực chất giúp ae vẫn ghi đậm dấu ấn của người đàn dông trưởng thành.",
                    "Chọn Size: Size M: 58kg-68kg Size L: 69kg-78kg Size XL:78kg- 88kg"],
        images: [
            `./assets/áo polo dài tay khoá kéo (đen trắng)/1.jpg`,
            `./assets/áo polo dài tay khoá kéo (đen trắng)/2.jpg`,
            `./assets/áo polo dài tay khoá kéo (đen trắng)/3.jpg`,
            `./assets/áo polo dài tay khoá kéo (đen trắng)/4.jpg`,
            `./assets/áo polo dài tay khoá kéo (đen trắng)/5.jpg`,
            `./assets/áo polo dài tay khoá kéo (đen trắng)/6.jpg`,
        ]
    },
    {
        id: 3,
        collection: "New Arrival",
        name: "Áo polo khoá kéo 3 màu (đen xám trắng)",
        collab: "Addidas",
        price: 310.000,
        start: 5,
        description: ["Cập bến cho các tín đồ yêu thích POLO trong giữa tháng 2 này đi chơi xuân. Mang phong cách Châu âu với kiểu dáng khoá kéo hiện đại thanh lịch giúp ae trở lên lịch sự, sang trọng trong mọi sự kiện, bữa tiệc. Vẫn chất liệu cotton co giãn 4 chiều giúp ae thoải mái tự do vận động, k gây ngứa khó chịu khi f mặc lâu.",
        "Form size từ 55-95kg| EU - với 3 màu: Đen/ Trắng/ Xám",
        "Suggest size: Size S: 55-68kg Size M: 68-77kg Size L: 78-87kg Size XL: 88-95kg"],
        images: [
            "./assets/Áo polo khoá kéo 3 màu (đen xám trắng)/1.jpg",
            "./assets/Áo polo khoá kéo 3 màu (đen xám trắng)/2.jpg",
            "./assets/Áo polo khoá kéo 3 màu (đen xám trắng)/3.jpg",
            "./assets/Áo polo khoá kéo 3 màu (đen xám trắng)/4.jpg",
            "./assets/Áo polo khoá kéo 3 màu (đen xám trắng)/5.jpg",
            "./assets/Áo polo khoá kéo 3 màu (đen xám trắng)/6.jpg",
        ]
    },
    {
        id: 4,
        collection: "New Arrival",
        name: "Áo sơ mi cổ trụ form slim fit (đen trắng)",
        collab: "Addidas",
        price: 460.000,
        start: 5,
        description: ["*Áo SƠ Mi cổ trụ cho các quý ông Bạn muốn trở nên thật LỊCH LÃM, PHONG ĐỘ vậy hãy để Amey giúp bạn nhé! Với chất liệu cotton 100% mịn màng, co giãn tốt, chuẩn form châu Âu cực sang.",
        " Size Suggest: Size S: từ 58Kg-67kg Size M: từ 68Kg-74kg Size L: từ 74Kg-81kg Size XL: từ 82Kg-90kg Size 2XL: từ 90Kg-100kg"],
        images: [
            "./assets/Áo sơ mi cổ trụ form slim fit (đen trắng)/1.jpg",
            "./assets/Áo sơ mi cổ trụ form slim fit (đen trắng)/2.jpg",
            "./assets/Áo sơ mi cổ trụ form slim fit (đen trắng)/3.jpg",
            "./assets/Áo sơ mi cổ trụ form slim fit (đen trắng)/4.jpg",
            "./assets/Áo sơ mi cổ trụ form slim fit (đen trắng)/5.jpg",
        ]
    },
    {
        id: 5,
        collection: "New Arrival",
        name: "Áo sơ mi form slimfit co giãn 4 chiều (đen trắng)",
        collab: "Addidas",
        price: 460.000,
        start: 5,
        description: ["Dành cho anh yêu thích thời trang Châu Âu classic. thì đây là kiểu áo mà anh không thể bỏ lỡ với form dáng Eu cùng chất liệu cotton cao cấp co giãn tuyệt đối giúp anh em mặc ôm gọn khoe dáng lại vô vùng thoải mái size từ 58kg-95kg luôn sẵn sàng cho anh em",
        "Size Suggest: Size S: từ 58Kg-67kg Size M: từ 68Kg-74kg Size L: từ 74Kg-81kg Size XL: từ 82Kg-90kg Size 2XL: từ 90Kg-100kg"],
        images: [
            "./assets/Áo sơ mi form slimfit co giãn 4 chiều (đen trắng)/1.jpg",
            "./assets/Áo sơ mi form slimfit co giãn 4 chiều (đen trắng)/2.jpg",
            "./assets/Áo sơ mi form slimfit co giãn 4 chiều (đen trắng)/3.jpg",
            "./assets/Áo sơ mi form slimfit co giãn 4 chiều (đen trắng)/4.jpg",
            "./assets/Áo sơ mi form slimfit co giãn 4 chiều (đen trắng)/5.jpg",
            "./assets/Áo sơ mi form slimfit co giãn 4 chiều (đen trắng)/6.jpg",
            "./assets/Áo sơ mi form slimfit co giãn 4 chiều (đen trắng)/7.jpg",
            "./assets/Áo sơ mi form slimfit co giãn 4 chiều (đen trắng)/8.jpg",
            "./assets/Áo sơ mi form slimfit co giãn 4 chiều (đen trắng)/9.jpg",
            "./assets/Áo sơ mi form slimfit co giãn 4 chiều (đen trắng)/10.jpg",
        ]
    },
    {
        id: 6,
        collection: "Shoes Collection",
        name: "Áo sơ mi ngắn tay  form slimfit co giãn 4 chiều",
        collab: "Addidas",
        price: 460.000,
        start: 5,
        description: ["Vẫn trung thành với chất cotton silk co giãn. Đem lại cảm giác thoải mái dễ chịu khi mặc cùng khả năng phối đồ biến ae thành những quý ông hoàn hảo, lịch lãm.",
        "Size Suggest: Size S: từ 58Kg-67kg Size M: từ 68Kg-74kg Size L: từ 74Kg-81kg Size XL: từ 82Kg-90kg Size 2XL: từ 90Kg-100kg"],
        images: [
            "./assets/Áo sơ mi ngắn tay  form slimfit co giãn 4 chiều/1.jpg",
            "./assets/Áo sơ mi ngắn tay  form slimfit co giãn 4 chiều/2.jpg",
            "./assets/Áo sơ mi ngắn tay  form slimfit co giãn 4 chiều/3.jpg",
            "./assets/Áo sơ mi ngắn tay  form slimfit co giãn 4 chiều/4.jpg",
            "./assets/Áo sơ mi ngắn tay  form slimfit co giãn 4 chiều/5.jpg",
        ]
    },
    {
        id: 7,
        collection: "Summer Sale",
        name: "áo tshirt oversize xám tro",
        collab: "Addidas",
        price: 260.000,
        start: 5,
        description: ["𝐎𝐯𝐞𝐫𝐬𝐢𝐳𝐞 𝐓𝐬𝐡𝐢𝐫𝐭 - 𝐆𝐫𝐞𝐲. Cho ra mắt màu mới dòng tshirt oversize trong tháng này cho anh em thích form áo rộng đậm chất tự do là phóng khoáng. Với kiểu màu xám khói form áo rộng cùng chất cotton mang lại cảm giác thoải mái khi mặc mà cực dễ phối đồ.",
        "Suggest size: Size S: 55-68kg Size M: 68-77kg Size L: 78-87kg Size XL: 88-95kg"],
        images: [
            "./assets/áo tshirt oversize xám tro/1.jpg",
            "./assets/áo tshirt oversize xám tro/2.jpg",
            "./assets/áo tshirt oversize xám tro/3.jpg",
            "./assets/áo tshirt oversize xám tro/4.jpg"
        ]
    },
    {
        id: 8,
        collection: "New Arrival",
        name: "Áo Tshirt slimfit cotton 100",
        collab: "Addidas",
        price: 260.000,
        start: 5,
        description: ["TBasic Tshirt for Gentleman v2.0. Dành cho những Quý Ông yêu trường phái CLASSIC nhưng muốn sự tinh tế giữ đc ấn tượng trong sự kiện qtrong. Amey đã mang đến cho phiên bản Tshirt mới với chất liệu Cotton Cao Cấp giúp ae mặc thoải mái thoáng mát. Size từ 58kg-95kg với Form dáng tinh tế của Châu Âu. Đây chính là lựa chọn k thể bỏ qua dành cho ae.",
        "Size Suggest: Size S: từ 58Kg-67kg Size M: từ 68Kg-74kgn Size L: từ 74Kg-81kg Size XL: từ 82Kg-95kg"],
        images: [
            "./assets/Áo Tshirt slimfit cotton 100/1.jpg",
            "./assets/Áo Tshirt slimfit cotton 100/2.jpg",
            "./assets/Áo Tshirt slimfit cotton 100/3.jpg",
            "./assets/Áo Tshirt slimfit cotton 100/4.jpg",
            "./assets/Áo Tshirt slimfit cotton 100/5.jpg",
            "./assets/Áo Tshirt slimfit cotton 100/6.jpg",
            "./assets/Áo Tshirt slimfit cotton 100/7.jpg",
        ]
    },
    {
        id: 9,
        collection: "Best choice for Winter",
        name: "chinos đen co giãn 4 chiều",
        collab: "Addidas",
        price: 350.000,
        start: 5,
        description: ["This Limited Edition printed t-shirt marks the rebirth of a phoenix. With a hand drawn design artwork symbolizing a greater resurrection of an immortal creature with our text detail featuring the new collection name and product details. Each layer is hand printed with care."],
        images: [
            "./assets/chinos đen co giãn 4 chiều/1.jpg",
            "./assets/chinos đen co giãn 4 chiều/2.jpg",
            "./assets/chinos đen co giãn 4 chiều/3.jpg",
        ]
    },
    {
        id: 10,
        collection: "Summer Sale",
        name: "Henly Light Wash",
        collab: "Addidas",
        price: 280.000,
        start: 5,
        description: ["[𝐍𝐄𝐖 𝐀𝐑𝐑𝐈𝐕𝐀𝐋] 𝐓𝐒𝐇𝐈𝐑𝐓 𝐂Ổ 𝐇𝐄𝐍𝐋𝐄𝐘.Hè này k đi được Tây Ba Nha - Majorca thì cũng phải ra biển chứ ae. Làm kiểu sơ mi này đi biển thì khỏi phải bàn nhé. Chất đũi thoáng mát, màu chuyển light cực đẹp, cực lạ, cực cuốn để ae đi chơi.Suggest size: Size S: 55-70kg Size M: 70-80kg Size L: 80-90kg"],
        images: [
            "./assets/henlyLightWash/1.jpg",
            "./assets/henlyLightWash/2.jpg",
            "./assets/henlyLightWash/3.jpg",
            "./assets/henlyLightWash/4.jpg",
            "./assets/henlyLightWash/5.jpg",
            "./assets/henlyLightWash/6.jpg",
        ]
    },
    {
        id: 11,
        collection: "Summer Sale",
        name: "oversize cổ lửng cotton (đen  trắng)",
        collab: "Addidas",
        price: 180.000,
        start: 5,
        description: ["🔺 𝐓𝐒𝐇𝐈𝐑𝐓 𝐎𝐕𝐄𝐑𝐒𝐈𝐙𝐄 𝐇𝐈𝐆𝐇 𝐍𝐄𝐂𝐊 Hè đến rồi chuẩn bị lên đồ đi chơi thôi ae. Mang đến cho ae phong cách cực Tây với form oversize cùng kiểu cổ cao. Với chất liệu cotton co giãn 4 chiều thoáng mát khi mặc cực dễ phối đồ cùng kiểu jeans hay Âu mang lại những kiểu style khác nhau. Form size S | M |L | XL cùng 2 màu back/white.",
        "Suggest size: size S: 55-60kg size M: 61-67kg size L: 68-75kg size XL: 76-83kg size 2XL: 84kg"],
        images: [
            "./assets/oversize cổ lửng cotton (đen  trắng)/1.jpg",
            "./assets/oversize cổ lửng cotton (đen  trắng)/2.jpg",
            "./assets/oversize cổ lửng cotton (đen  trắng)/3.jpg",
            "./assets/oversize cổ lửng cotton (đen  trắng)/4.jpg",
            "./assets/oversize cổ lửng cotton (đen  trắng)/5.jpg",
            "./assets/oversize cổ lửng cotton (đen  trắng)/6.jpg",
            "./assets/oversize cổ lửng cotton (đen  trắng)/7.jpg",
        ]
    },
    {
        id: 12,
        collection: "New Arrival",
        name: "quần âu đen cropped co giãn 4 chiều",
        collab: "Addidas",
        price: 360.000,
        start: 5,
        description: ["Quần Âu Đen slim cropped - CỨU TINH CHO CÁC CHÀNG \"NẤM LÙN\"❤️Amey mang đến cho ae quần kẻ phiên bản slim cropped với ống ngắn đến mắt cá chân giúp cho cảm giác đôi chân dài hơn như H.ack chiều cao. Với form dáng HIỆN ĐẠI - NĂNG ĐỘNG dễ dàng kết hợp các kiểu giày lười cho đến sneaker hay các kiểu áo khác nhau. Một lợi thế cho ae phối đồ để phù hợp từng hoàn cảnh đi chơi. Chất liệu từ thun 4 chiều giúp thoáng mát thấm hút cao cũng như co giãn đàn hồi cực tốt. Form size từ 58kg-95kg|EU đã có sẵn trên kệ.","Size Suggest: Size S: từ 55Kg-60kg |1m60- 1m65 Size M: từ 60Kg-67kg |1m63- 1m68 Size L: từ 67Kg-74kg |1m65- 1m70 Size XL: từ 75Kg-80kg |1m70- 1m78"],
        images: [
            "./assets/quần âu đen cropped co giãn 4 chiều/1.jpg",
            "./assets/quần âu đen cropped co giãn 4 chiều/2.jpg",
            "./assets/quần âu đen cropped co giãn 4 chiều/3.jpg",
        ]
    },
    {
        id: 13,
        collection: "New Arrival",
        name: "quần âu kẻ caro co giãn 4 chiều",
        collab: "Addidas",
        price: 430.000,
        start: 5,
        description: ["Quần kẻ caro slim cropped - CỨU TINH CHO CÁC CHÀNG \"NẤM LÙN\"❤️ Amey mang đến cho ae quần kẻ phiên bản slim cropped với ống ngắn đến mắt cá chân giúp cho cảm giác đôi chân dài hơn như H.ack chiều cao. Với form dáng HIỆN ĐẠI - NĂNG ĐỘNG dễ dàng kết hợp các kiểu giày lười cho đến sneaker hay các kiểu áo khác nhau. Một lợi thế cho ae phối đồ để phù hợp từng hoàn cảnh đi chơi. Chất liệu từ U-mi + spandex giúp thoáng mát thấm hút cao cũng như co giãn đàn hồi cực tốt quá phù hợp với đất nước nóng ẩm như chúng ta. Form size từ 58kg-95kg|EU đã có sẵn trên kệ",
        "Size Suggest: Size S: từ 58Kg-65kg |1m60- 1m65 Size M: từ 65Kg-70kg |1m63- 1m68 Size L: từ 70Kg-75kg |1m65- 1m70 Size XL: từ 75Kg-80kg |1m70- 1m78"],
        images: [
            "./assets/quần âu kẻ caro co giãn 4 chiều/1.jpg",
            "./assets/quần âu kẻ caro co giãn 4 chiều/2.jpg",
            "./assets/quần âu kẻ caro co giãn 4 chiều/3.jpg",
        ]
    },
    {
        id: 14,
        collection: "Summer Sale",
        name: "quần âu xám co giãn 4 chiều",
        collab: "Addidas",
        price: 360.000,
        start: 5,
        description: ["Quần Âu XÁM slim cropped - CỨU TINH CHO CÁC CHÀNG \"NẤM LÙN\"❤️ Amey mang đến cho ae quần kẻ phiên bản slim cropped với ống ngắn đến mắt cá chân giúp cho cảm giác đôi chân dài hơn như H.ack chiều cao.Với form dáng HIỆN ĐẠI - NĂNG ĐỘNG dễ dàng kết hợp các kiểu giày lười cho đến sneaker hay các kiểu áo khác nhau. Một lợi thế cho ae phối đồ để phù hợp từng hoàn cảnh đi chơi.Chất liệu từ COTTON giúp thoáng mát thấm hút cao cũng như co giãn đàn hồi cực tốt quá phù hợp với đất nước nóng ẩm như chúng ta. Form size từ 58kg-95kg|EU đã có sẵn trên kệ.",
        " Size Suggest: Size S: từ 58Kg-65kg |1m60- 1m65 Size M: từ 65Kg-70kg |1m63- 1m68 Size L: từ 70Kg-75kg |1m65- 1m70 Size XL: từ 75Kg-80kg |1m70- 1m78"],
        images: [
            "./assets/quần âu xám co giãn 4 chiều/1.jpg",
            "./assets/quần âu xám co giãn 4 chiều/2.jpg",
            "./assets/quần âu xám co giãn 4 chiều/3.jpg",
            "./assets/quần âu xám co giãn 4 chiều/4.jpg",
        ]
    },
    {
        id: 15,
        collection: "Summer Sale",
        name: "short jean rách co giãn 4 chiều (xanh đen)",
        collab: "Addidas",
        price: 360.000,
        start: 5,
        description: ["📢[𝐔𝐩𝐠𝐚𝐫𝐝𝐞]- 𝐒𝐡𝐨𝐫𝐭 𝐉𝐞𝐚𝐧𝐬 𝐕𝟑.𝟎 Trở lại với short jeans rách cho ae ít hàng mới. Co giãn hơn- vải mềm hơn - chất vải lì hơn."],
        images: [
            "./assets/short jean rách co giãn 4 chiều (xanh đen)/1.jpg",
            "./assets/short jean rách co giãn 4 chiều (xanh đen)/2.jpg",
            "./assets/short jean rách co giãn 4 chiều (xanh đen)/3.jpg",
            "./assets/short jean rách co giãn 4 chiều (xanh đen)/4.jpg",
            "./assets/short jean rách co giãn 4 chiều (xanh đen)/5.jpg",
            "./assets/short jean rách co giãn 4 chiều (xanh đen)/6.jpg",
            "./assets/short jean rách co giãn 4 chiều (xanh đen)/7.jpg",
            "./assets/short jean rách co giãn 4 chiều (xanh đen)/8.jpg",
        ]
    },
    {
        id: 16,
        collection: "Summer Sale",
        name: "short jeans trơn co giãn 4 chiều (đen xanh)",
        collab: "Addidas",
        price: 360.000,
        start: 5,
        description: ["ĐÓN HÈ CÙNG SLIM DENIM SHORT Hè tới rồi các quý ông đã chuẩn bị gì cho mùa du lịch, đi chơi chưa? Amey mang tới cho anh em short jeans với chất vải mềm co giãn cùng phong cách Châu Âu - HIỆN ĐẠI sẽ là chiếc quần trong hè này không thể bỏ lỡ để đi chơi.",
        " Size từ 55kg-100kg EU form ôm đùi cùng style gấu lơ-vê cho các Quý Ông đã sẵn sàng "],
        images: [
            "./assets/short jeans trơn co giãn 4 chiều (đen xanh)/1.jpg",
            "./assets/short jeans trơn co giãn 4 chiều (đen xanh)/2.jpg",
            "./assets/short jeans trơn co giãn 4 chiều (đen xanh)/3.jpg",
            "./assets/short jeans trơn co giãn 4 chiều (đen xanh)/4.jpg",
            "./assets/short jeans trơn co giãn 4 chiều (đen xanh)/5.jpg",
            "./assets/short jeans trơn co giãn 4 chiều (đen xanh)/6.jpg",
            "./assets/short jeans trơn co giãn 4 chiều (đen xanh)/7.jpg",
            "./assets/short jeans trơn co giãn 4 chiều (đen xanh)/8.jpg",
            "./assets/short jeans trơn co giãn 4 chiều (đen xanh)/9.jpg",
            "./assets/short jeans trơn co giãn 4 chiều (đen xanh)/10.jpg",
        ]
    },
    {
        id: 17,
        collection: "Summer Sale",
        name: "skinny jean rách các loại (đen xanh)",
        collab: "Addidas",
        price: 550.000,
        start: 5,
        description: ["● MUST HAVE IT| RIPPED BLACK JEANS Tăng thêm bộ Sưu tập tủ đồ cho các quý ông bằng jean rách gấu/gối k thể bỏ qua. Vẫn là chất liệu cao cấp co giãn cùng với form skinny ôm đến mắt cá chân cho ae cảm giác Hiện đại - Thanh lịch- Tinh tế trong các cuộc đi chơi, sự kiện. Size 58kg-95kg EU style đậm chất Châu Âu giúp ae lựa chọn dễ dàng kiểu dáng.",
        " Size Suggest: Size S: từ 58Kg-68kg |1m60- 1m65 Size M: từ 69Kg-77kg |1m70- 1m75 Size L: từ 78Kg-85kg |1m75- 1m80 Size XL: từ 86Kg-93kg |1m78- 1m83 Size 2XL: từ 93Kg-100kg |1m80- 1m85"],
        images: [
            "./assets/skinny jean rách các loại (đen xanh)/1.jpg",
            "./assets/skinny jean rách các loại (đen xanh)/2.jpg",
            "./assets/skinny jean rách các loại (đen xanh)/3.jpg",
            "./assets/skinny jean rách các loại (đen xanh)/4.jpg",
            "./assets/skinny jean rách các loại (đen xanh)/5.jpg",
            "./assets/skinny jean rách các loại (đen xanh)/6.jpg",
            "./assets/skinny jean rách các loại (đen xanh)/7.jpg",
            "./assets/skinny jean rách các loại (đen xanh)/8.jpg",
            "./assets/skinny jean rách các loại (đen xanh)/9.jpg",
        ]
    },
    {
        id: 18,
        collection: "Summer Sale",
        name: "skinny jeans đen rách khoá kéo(gối+đùi) co giãn 4 chiều",
        collab: "Addidas",
        price: 550.000,
        start: 5,
        description: ["[NEW ARRIVAL] SUPER SKINNYJEANS. Xứng đáng là con quái vật trong dòng jeans. Anh em nào đã chán với kiểu công sở \"đóng thùng\" hàng ngày đầy khuôn mẫu thì Amey mang đến cho kiểu quần jeans đậm chất nam tính, bụi bặm kiểu street boiz.Vẫn là chất liệu cotton spandex co giãn 4 chiều mang lại cảm giác thoải mái dễ chịu không co cứng vải khi mặc.",
        "Ae lẹ tay cmt/ib để nhận tư vấn sp Size S: từ 58Kg-68kg |1m60- 1m65 Size M: từ 69Kg-77kg |1m70- 1m75 Size L: từ 78Kg-85kg |1m75- 1m80 Size XL: từ 86Kg-93kg |1m78- 1m83 Size 2XL: từ 93Kg-100kg |1m80- 1m85"],
        images: [
            "./assets/skinny jeans đen rách khoá kéo(gối+đùi) co giãn 4 chiều/1.jpg",
            "./assets/skinny jeans đen rách khoá kéo(gối+đùi) co giãn 4 chiều/2.jpg",
            "./assets/skinny jeans đen rách khoá kéo(gối+đùi) co giãn 4 chiều/3.jpg",
        ]
    },
    {
        id: 19,
        collection: "New Arrival",
        name: "skinny jeans rách gối co giãn chiều(đen xanh)",
        collab: "Addidas",
        price: 550.000,
        start: 5,
        description: ["DONT MISSING| SKINNY JEANS. Vẫn là chất liệu cao cấp co giãn 4 chiều mang lại cảm giác co giãn cực tốt cùng với form skinny ôm đến mắt cá chân hướng tới phong cách Hiện đại - Thanh lịch- Tinh tế trong các cuộc đi chơi, sự kiện. Size 58kg-95kg EU style đậm chất Châu Âu giúp ae lựa chọn dễ dàng kiểu dáng.",
        "Size Suggest: Size S: từ 58Kg-68kg |1m60- 1m65 Size M: từ 69Kg-77kg |1m70- 1m75 Size L: từ 78Kg-85kg |1m75- 1m80 Size XL: từ 86Kg-93kg |1m78- 1m83 Size 2XL: từ 93Kg-100kg |1m80- 1m85"],
        images: [
            "./assets/skinny jeans rách gối co giãn chiều(đen xanh)/1.jpg",
            "./assets/skinny jeans rách gối co giãn chiều(đen xanh)/2.jpg",
            "./assets/skinny jeans rách gối co giãn chiều(đen xanh)/3.jpg",
            "./assets/skinny jeans rách gối co giãn chiều(đen xanh)/4.jpg",
            "./assets/skinny jeans rách gối co giãn chiều(đen xanh)/5.jpg",
            "./assets/skinny jeans rách gối co giãn chiều(đen xanh)/6.jpg",
            "./assets/skinny jeans rách gối co giãn chiều(đen xanh)/7.jpg",
            "./assets/skinny jeans rách gối co giãn chiều(đen xanh)/8.jpg",
            "./assets/skinny jeans rách gối co giãn chiều(đen xanh)/9.jpg",
            "./assets/skinny jeans rách gối co giãn chiều(đen xanh)/10.jpg",
        ]
    },
    {
        id: 20,
        collection: "New Arrival",
        name: "skinny jeans trắng rách co giãn 4 chiều",
        collab: "Addidas",
        price: 550.000,
        start: 5,
        description: ["𝙐𝙋𝙂𝘼𝙍𝘿𝙀- 𝙉𝙚𝙬 𝘾𝙤𝙡𝙤𝙧 - 𝙎𝙆𝙄𝙉𝙉𝙔 𝙅𝙀𝘼𝙉𝙎 𝙉𝘼𝙈. Vẫn mang đến thương hiệu skinny Jean ôm chân CO GIÃN 4 CHIỀU trong suốt thời gian qua.Hiện Amey đã update thêm 2 màu mới TRẮNG/ XANH ĐẬM dòng jeans rách cho ae thêm sự lựa chọn đi chơi.",
        "Size Suggest: Size S: từ 58Kg-68kg |1m60- 1m65 Size M: từ 69Kg-77kg |1m70- 1m75 Size L: từ 78Kg-85kg |1m75- 1m80 Size XL: từ 86Kg-93kg |1m78- 1m83 Size 2XL: từ 93Kg-100kg |1m80- 1m85"],
        images: [
            "./assets/skinny jeans trắng rách co giãn 4 chiều/1.png",
            "./assets/skinny jeans trắng rách co giãn 4 chiều/2.png",
            "./assets/skinny jeans trắng rách co giãn 4 chiều/3.png",
        ]
    },
    {
        id: 21,
        collection: "Best Choice for Winter",
        name: "skinny jeans trơn co giãn 4 chiều (đen xanh)",
        collab: "Addidas",
        price: 100,
        start: 5,
        description: ["This Limited Edition printed t-shirt marks the rebirth of a phoenix. With a hand drawn design artwork symbolizing a greater resurrection of an immortal creature with our text detail featuring the new collection name and product details. Each layer is hand printed with care."],
        images: [
            "./assets/skinny jeans trơn co giãn 4 chiều (đen xanh)/1.jpg",
            "./assets/skinny jeans trơn co giãn 4 chiều (đen xanh)/2.jpg",
            "./assets/skinny jeans trơn co giãn 4 chiều (đen xanh)/3.jpg",
            "./assets/skinny jeans trơn co giãn 4 chiều (đen xanh)/4.jpg",
            "./assets/skinny jeans trơn co giãn 4 chiều (đen xanh)/5.jpg",
            "./assets/skinny jeans trơn co giãn 4 chiều (đen xanh)/6.jpg",
            "./assets/skinny jeans trơn co giãn 4 chiều (đen xanh)/7.jpg",
            "./assets/skinny jeans trơn co giãn 4 chiều (đen xanh)/8.jpg",
            "./assets/skinny jeans trơn co giãn 4 chiều (đen xanh)/9.jpg",
        ]
    },
    {
        id: 22,
        collection: "Best Choice for Winter",
        name: "skinny Jeans xám tro rách co giãn 4 chiều",
        collab: "Addidas",
        price: 100,
        start: 5,
        description: ["This Limited Edition printed t-shirt marks the rebirth of a phoenix. With a hand drawn design artwork symbolizing a greater resurrection of an immortal creature with our text detail featuring the new collection name and product details. Each layer is hand printed with care."],
        images: [
            "./assets/skinny Jeans xám tro rách co giãn 4 chiều/1.jpg",
            "./assets/skinny Jeans xám tro rách co giãn 4 chiều/2.jpg",
            "./assets/skinny Jeans xám tro rách co giãn 4 chiều/3.jpg",
            "./assets/skinny Jeans xám tro rách co giãn 4 chiều/4.jpg",
            "./assets/skinny Jeans xám tro rách co giãn 4 chiều/5.jpg",
            "./assets/skinny Jeans xám tro rách co giãn 4 chiều/6.jpg",
            "./assets/skinny Jeans xám tro rách co giãn 4 chiều/7.jpg",
        ]
    },
    {
        id: 23,
        collection: "Best Choice for Winter",
        name: "skinny Jeans xám tro rách gấu + gối khoá kéo",
        collab: "Addidas",
        price: 100,
        start: 5,
        description: ["This Limited Edition printed t-shirt marks the rebirth of a phoenix. With a hand drawn design artwork symbolizing a greater resurrection of an immortal creature with our text detail featuring the new collection name and product details. Each layer is hand printed with care."],
        images: [
            "./assets/skinny Jeans xám tro rách gấu + gối khoá kéo/1.jpg",
            "./assets/skinny Jeans xám tro rách gấu + gối khoá kéo/2.jpg",
            "./assets/skinny Jeans xám tro rách gấu + gối khoá kéo/3.jpg",
            "./assets/skinny Jeans xám tro rách gấu + gối khoá kéo/4.jpg",
        ]
    },
    {
        id: 24,
        collection: "Best Choice for Winter",
        name: "skinny jeans xanh rách (gối+đùi) co giãn 4 chiều",
        collab: "Addidas",
        price: 100,
        start: 5,
        description: ["This Limited Edition printed t-shirt marks the rebirth of a phoenix. With a hand drawn design artwork symbolizing a greater resurrection of an immortal creature with our text detail featuring the new collection name and product details. Each layer is hand printed with care."],
        images: [
           "./assets/skinny jeans xanh rách (gối+đùi) co giãn 4 chiều/1.png",
           "./assets/skinny jeans xanh rách (gối+đùi) co giãn 4 chiều/2.png",
           "./assets/skinny jeans xanh rách (gối+đùi) co giãn 4 chiều/3.png",
           "./assets/skinny jeans xanh rách (gối+đùi) co giãn 4 chiều/4.png",
           "./assets/skinny jeans xanh rách (gối+đùi) co giãn 4 chiều/5.png",
           "./assets/skinny jeans xanh rách (gối+đùi) co giãn 4 chiều/6.png",
           "./assets/skinny jeans xanh rách (gối+đùi) co giãn 4 chiều/7.png",
           "./assets/skinny jeans xanh rách (gối+đùi) co giãn 4 chiều/8.png",
           "./assets/skinny jeans xanh rách (gối+đùi) co giãn 4 chiều/9.png",
           "./assets/skinny jeans xanh rách (gối+đùi) co giãn 4 chiều/10.png",
           "./assets/skinny jeans xanh rách (gối+đùi) co giãn 4 chiều/11.png",
        ]
    },

]

export const collection = [
    {
        id: 1,
        event: "New Arrival",
        image: "./assets/collection1.png",
        description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consequuntur aliquid voluptas, incidunt beatae reprehenderit obcaecati veritatis ipsam officiis magnam ex earum ratione adipisci natus enim quia esse accusamus commodi quibusdam!"
    },
    {
        id: 2,
        event: "Best Choice for Winter",
        image: "./assets/collection2.png",
        description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consequuntur aliquid voluptas, incidunt beatae reprehenderit obcaecati veritatis ipsam officiis magnam ex earum ratione adipisci natus enim quia esse accusamus commodi quibusdam!"
    },
    {
        id: 3,
        event: "Summer Sale",
        image: "./assets/collection3.png",
        description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consequuntur aliquid voluptas, incidunt beatae reprehenderit obcaecati veritatis ipsam officiis magnam ex earum ratione adipisci natus enim quia esse accusamus commodi quibusdam!"
    },
    {
        id: 4,
        event: "Shoes Collection",
        image: "./assets/collection4.png",
        description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consequuntur aliquid voluptas, incidunt beatae reprehenderit obcaecati veritatis ipsam officiis magnam ex earum ratione adipisci natus enim quia esse accusamus commodi quibusdam!"
    },
]